### ISSUE TITLE
Bessere Kommentare im Wiki bitte

### ISSUE THREAD

**Issue by LeonWilzer** [lukaslangrock/nigeria-history#1]
Das Wiki braucht mehr Features im Kommentarberreich. Musikdateien in base64 direkt vom Kommentar aus abzuspielen wäre cool.

**Comment by lukaslangrock** [comment]
I am sorry to hear that you are unhappy with one of my services. Please note that this repository was not meant for general purpose issues regarding langrock.info, but instead just for https://nigeria.langrock.info.

Thank you for understanding.
